# Generated by Django 3.0.6 on 2020-05-09 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bud', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
