# Generated by Django 3.0.6 on 2020-05-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bud', '0002_auto_20200525_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
