# Generated by Django 3.0.6 on 2020-05-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200525_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dp',
            field=models.ImageField(blank=True, default='placeholders/usr/avatar-1577909.svg', upload_to='users/dp/', verbose_name='Display Pic'),
        ),
    ]
