# Generated by Django 3.0.6 on 2020-05-24 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dp', models.ImageField(blank=True, default='placeholders/usr/avatar-1577909.svg', upload_to='users/dp/', verbose_name='Display Pic')),
            ],
        ),
    ]
